// Code generated by struct2interface; DO NOT EDIT.

package cache

import (
	"context"
	"time"
)

// CacheInterface ...
type CacheInterface interface {
	// Get Redis `GET key` command. It returns redis.Nil error when key does not exist.
	Get(ctx context.Context, key string) (string, error)
	// Set Redis `SET key value` command.
	Set(ctx context.Context, key string, value interface{}, expiration time.Duration) error
	// Del Redis `DEL key` command.
	Del(ctx context.Context, keys ...string) error
}
