# 默认日志的配置
[logger.default]
	debug = false
# 系统日志的配置
[logger.ego]
	debug = true

[redis.marmot]
	debug                      = true             # ego增加redis debug，打开后可以看到，配置名、地址、耗时、请求数据、响应数据
	addr                       = "127.0.0.1:6379" #地址 sh-crs-bhv5nqjd.sql.tencentcdb.com:24826
	password                   = "foobared"       # 密码 "office0918"
	mode                       = "stub"           # 默认为stub单实例模式，可选"stub|cluster|sentinel"
	db                         = 0
	enableAccessInterceptor    = true
	enableAccessInterceptorReq = true
	enableAccessInterceptorRes = true
