// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package worker

import (
	"demo/pkg/redis/cache"
	"demo/pkg/redis/option"
)

// Injectors from wire.go:

func InitWorker() (*Worker, func(), error) {
	optionOption := option.New()
	cacheInterface := cache.NewCache(optionOption)
	workerOption := &Option{
		Cache: cacheInterface,
	}
	worker := NewWorker(workerOption)
	return worker, func() {
	}, nil
}
